### ISSUE TITLE
container package

### ISSUE THREAD

**Issue by guumaster** [fp-dom/meta#10]
Are you considering making a unique package with all the fp-\* dependencies to install once and be able to impor all the tools instead of installing 10 or so packages?

**Comment by hemanth** [comment]
No, the idea is to have tiny independent modules, are you finding a need to have all of them as dependencies?

**Comment by guumaster** [comment]
It's just that if you need one method to touch DOM, probably you'll need more. And I don't see much difference with the 1-liners. And you could end up with:

```
import { contains, append , elem } from 'fp-dom'; 

// instead of

import { contains } from 'fd-contains';
import { append } from 'fd-append';
import { elem } from 'fd-elem'; 
```

Or you prefer to make a specific `fd-*` container module for every project?

**Comment by hemanth** [comment]
I would still vote for individual modules. @stoeffel What's your view?

**Comment by stoeffel** [comment]
Me too, but it would be okay for me to have a container module. @guumaster If you want you can create such a module and transfer it to the org later. okay for you @hemanth?

**Comment by hemanth** [comment]
:+1:

**Comment by guumaster** [comment]
I've made [this](https://www.npmjs.com/package/fp-dom) and added to npm. If want I can transfer the repo to the org and add you both to npm ownership.

What I'm not sure how to tackle is automation when a new sub-module is updated. Any ideas?

**Comment by hemanth** [comment]
Nice @guumaster  :+1: 

Well to automate it, we must play a bit with github APIs nice problem to solve.

**Comment by guumaster** [comment]
I'm not too familiar with that kind of automation. 

Regarding transfer. I've tried, but couldn't transfer it. Would you add me to the org? Or you prefer that I transfer it to any of you?

**Comment by stoeffel** [comment]
adding you to the org is fin for me.
@hemanth ?

**Comment by hemanth** [comment]
Definitely adding to org makes sense!

**Comment by stoeffel** [comment]
@guumaster I added you to the org.

**Comment by guumaster** [comment]
:+1: thanks
