### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by stoeffel** [fp-dom/meta#2]
This is an API example of addClass, but the basic idea can be applied to other functions too.
Two points are important:
- (most) functions take functions as arguments
- (most) functions return curryied functions.
# addClass

``` js
// addClass(getClass:Function(index:Int) --> String, getElements:Function() --> NodeLIst);

var setDisabled = addClass(always('disabled'));

setDisabled(query('.item'));

var alternate = addClass(function(index) {
  return (index % 2 === 0)?'even' : 'odd';
});

alternate(query('li'));
```

**Comment by hemanth** [comment]
@stoeffel Still interested?
