### ISSUE TITLE
DOM query

### ISSUE THREAD

**Issue by stoeffel** [fp-dom/meta#3]
What are our plans for DOM querying?
Should it just be shorthands for browser functions or how should we make it different?

``` js
var query = require('fd-query').query; 
query === document.querySelector; // => true

var byId = require('fd-query').byId; 
byId === document.document.getElementById; // => true

```

**Comment by hemanth** [comment]
I would vote for: 

``` js

var query = require('fd-query');

query('#id');

query('.class');

query('.any .complex > selector');

// All returns an array instead of a NodeList :)

```

And later it can be curried with other functions as well.

**Comment by stoeffel** [comment]
SGTM

**Comment by hemanth** [comment]
It would be great if we could break down this further:
- fd-select -> would just do the selection. 
- fd-delegate -> would delegate
- fd-style -> would operate on styles.
- fd-animate -> would animate the dom element.
- fd-show and fd-hide.
- fd-event 

so on...
