### ISSUE TITLE
Events API

### ISSUE THREAD

**Issue by stoeffel** [fp-dom/meta#5]
How should we implement `fd-listener`?

`listen(event:String, handler:Function, elements:Array)`
or
`listen(handler:Function, event:String, elements:Array)`

Example

``` js
var onClick = listen('click');
var onClickCount = onClick((event) => {
  event.target.innerHTML = "click count: " + event.detail;
});

onClickCount(select('.counter'));
```

**Comment by hemanth** [comment]
`listen(event:String, handler:Function, elements:Array)` is intuitive, but is it functional enough?

**Comment by stoeffel** [comment]
`listen(event:String, handler:Function, elements:Array)`

That's what I favour too. Yes, I think it's FP enough.

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
- [x] fd-listen
- [ ] fd-listener
- [ ] fd-event
- [ ] fd-on

I' prefer fd-listen

**Comment by hemanth** [comment]
`fd-listen` sounds fine, we might alias it to `on` maybe?

**Comment by stoeffel** [comment]
Done
