### ISSUE TITLE
Virtual DOM

### ISSUE THREAD

**Issue by stoeffel** [fp-dom/meta#9]
We should think about how we make fp-dom work with virtual DOM.

**Comment by hemanth** [comment]
^ Long awaited.

**Comment by buzzdecafe** [comment]
:+1:

**Comment by hemanth** [comment]
Not sure if [to-vdom](https://github.com/hemanth/to-vdom) could help us in anyway.

**Comment by stoeffel** [comment]
### Todo
- [x] isVdom
- [x] virtual-elem
- [ ] render

**Comment by stoeffel** [comment]
Do we need a `render` function?
Using `virtual-dom/create-element` is already FP. Or what should it do different?
What else do we need for vdom?

**Comment by hemanth** [comment]
I would vote for a render function, along with say `toHTML`

Given:

``` js
{
  type : string | class,
  props : { children, className, etc. },
  key : string | boolean | number | null,
  ref : string | null
}
```

We must be able to do a `vdom` and then `dom` out of it.

Also, we can have a `patch` function.
